# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1  # if using IPv6

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_cloud_map_extractor_host
    token: !secret xiaomi_cloud_map_extractor_token
    username: !secret xiaomi_cloud_map_extractor_username
    password: !secret xiaomi_cloud_map_extractor_password
    country: "us"
    name: "Toby Map"
    draw: ['all']
    attributes:
      - calibration_points
      - room_numbers
    scan_interval:
      seconds: 300
    store_map_image: true
