clean_kitchen_and_hallway:
  alias: Clean Kitchen and Hallway
  sequence:
  - target:
      entity_id: vacuum.toby
    data:
      command: app_segment_clean
      params:
        - 20
        - 22
    action: vacuum.send_command

